name = "router-worker-edge"
main = "src/index.ts"
compatibility_date = "2024-09-13"

# Set to your Connector origin for CORS pinning. Use "*" for open CORS (no credentials).
[vars]
CONNECTOR_ORIGIN = "*"

bindings = [
	{ name = "SESSION_DO", class_name = "SessionDO" }
]

[env.production]
name = "router-worker-edge-production"
# Vars are not inherited by environments; repeat here or set a real origin for prod.
[env.production.vars]
CONNECTOR_ORIGIN = "*"

[env.production.durable_objects]
bindings = [
	{ name = "SESSION_DO", class_name = "SessionDO" }
]

[[env.production.migrations]]
tag = "v1"
new_sqlite_classes = ["SessionDO"]
